controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_controllers:
    resource:
        path: ../src/Controller/admin/
        namespace: App\Controller\Admin
    type: attribute
